version: '{build}'
clone_folder: c:\projects\wgui
image:
- Visual Studio 2019
configuration:
- Release
#- Debug

matrix:
  fast_finish: true

init:
- set arch=
- if "%arch%"=="Win64" ( set arch= Win64)
- echo %arch%
- echo %APPVEYOR_BUILD_WORKER_IMAGE%
- if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019%arch%" )
- echo %generator%

before_build:
- cmd: |-
    git submodule update --init
# download GLM https://glm.g-truc.net
- cmd: |-
    cd c:\projects\
    curl -LJO https://github.com/g-truc/glm/releases/download/0.9.9.8/glm-0.9.9.8.zip
    7z x glm-0.9.9.8.zip
    dir
- cmd: |-
    cd c:\projects\wgui
    mkdir build
    cd build
    cmake --version
    cmake .. -G %generator% -DDEPENDENCY_GLM_INCLUDE=c:\projects\glm
build:
  project: c:\projects\wgui\build\wgui.sln
  verbosity: normal
  parallel: true